# -*- coding: utf-8 -*-
import os

# SLACK BOT TOKEN
SLACK_BOT_UESR_TOKEN = os.environ["SLACK_BOT_UESR_TOKEN"]
SLACK_AUTH_TOKEN = os.environ["SLACK_AUTH_TOKEN"]
# SLACK OAUTH
SLACK_CLIENT_ID = os.environ["SLACK_CLIENT_ID"]
SLACK_CLIENT_SECRET = os.environ["SLACK_CLIENT_SECRET"]
SLACK_VERIFICATION_TOKEN = os.environ["SLACK_VERIFICATION_TOKEN"]